quarkus.datasource."dbos-db".db-kind=postgresql
quarkus.datasource."dbos-db".username = postgres
quarkus.datasource."dbos-db".password = dbos
quarkus.datasource."dbos-db".jdbc.url = jdbc:postgresql://localhost:5432/dbos_dev
quarkus.datasource."dbos-db".jdbc.transactions=disabled

quarkus.dbos.datasource=dbos-db
quarkus.dbos.app-name=quarkus-dbos-starter
quarkus.dbos.executor-id=main-executor
quarkus.dbos.queues."exampleQueue".concurrency=1