quarkus.dbos.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dbos_starter
quarkus.dbos.datasource.username=postgres
quarkus.dbos.datasource.password=dbos
quarkus.dbos.datasource.schema=dbos_starter
quarkus.dbos.app-name=quarkus-dbos-starter
quarkus.dbos.executor-id=main-executor